variables:

  TWINE_PASSWORD: ${CI_JOB_TOKEN}
  TWINE_USERNAME: gitlab-ci-token
  TWINE_REPO_URL: https://git.geomar.de/api/v4/projects/${CI_PROJECT_ID}/packages/pypi

stages:
  - build
  - test
  - release

build_wheel:
  stage: build
  image: python:3.10
  script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/*.whl

test_package:
  stage: test
  image: python:3.10
  script:
    - python -V
    - pip install -r requirements.txt  
    - python -m unittest discover -s tests  
    
  dependencies:
    - build_wheel
  artifacts:
    paths:
      - tests/test_results.xml

upload_package:
  stage: release
  script:
    - pip install twine
    - twine upload --verbose --repository-url $TWINE_REPO_URL dist/*
  dependencies:
    - build_wheel
  only:
    - main
    - tags
  allow_failure: false # uploading same version results in failure.